### ISSUE TITLE
openEuler镜像源申请加入南阳理工学院开源镜像站

### ISSUE THREAD

**Issue by zhang-jian-jun** [NYIST-OSUG/mirror-help#1]
镜像名:
openEuler官方镜像源

上游源（官方镜像）的地址
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

镜像简介
南阳理工学院开源镜像站点，你们好！
我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！

我们提供openEuler镜像同步指令如下:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)
镜像大小:
多个版本共600G

openEuler社区基础设施团队
[1]: https://openeuler.org/zh/
[2]: https://repo.openeuler.org/

**Comment by DefiedParty** [comment]
openEuler社区基础设施团队，你们好！
首先感谢您对南阳理工学院开源镜像站的支持。
很抱歉，目前由于服务器资源的限制，我们暂时无法立即支持openEuler社区的镜像。
在未来服务器资源得到扩充时，我们将提供openEuler社区的镜像。

**Comment by zhang-jian-jun** [comment]
好的，非常感谢哈！

**Comment by DefiedParty** [comment]
服务器扩容，已添加！
