### ISSUE TITLE
Termux镜像源申请加入南阳理工学院开源镜像站

### ISSUE THREAD

**Issue by 2096779623** [NYIST-OSUG/mirror-help#2]
# 镜像名:
Termux官方镜像源

# 镜像简介
Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。

# 镜像大小
15GB

# 同步方式
https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories

**Comment by DefiedParty** [comment]
已添加！
